name: imp_trading_chart
description: >
  A high-performance trading chart engine for Flutter with CustomPainter rendering, optimized for large datasets, real-time updates, and smooth pan & zoom.

version: 0.1.1

homepage: https://github.com/rahul-cse-25/imp_trading_chart

#screenshots:
#  - description: Trading chart with live updates
#    path: screenshots/pub/pub_dev.png

topics:
  - charts
  - trading
  - finance
  - visualization
  - flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Pure rendering & chart engine package.
# No bundled assets or platform-specific resources.
